/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.code;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

import static org.junit.jupiter.api.Assertions.assertEquals;

class AppTest {
    final String filePath1 = "./src/test/resources/filepath1.json";
    final String filePath2 = "./src/test/resources/filepath2.json";

    final String pathfile3 = "./src/test/resources/filepath1.yml";
    final String pathfile4 = "./src/test/resources/filepath2.yml";

    public static String getData(String path) throws IOException {
        return  Files.readString(Paths.get(path).toAbsolutePath().normalize());
    }
    @Test
    void jsonTest() throws Exception {
        String expect = getData("./src/test/resources/jsonTestResult.txt");

        String actual = Differ.generate(filePath1, filePath2, "json");
        assertEquals(expect, actual);
    }

    @Test
    void stylishTest() throws Exception {
        String expect = getData("./src/test/resources/stylishTestResult.txt");

        String actual = Differ.generate(filePath1, filePath2, "stylish");
        assertEquals(expect, actual);
    }

    @Test
    void ymlTest() throws Exception {
        String expect = getData("./src/test/resources/stylishTestResult.txt");

        String actual = Differ.generate(pathfile3, pathfile4);

        assertEquals(expect, actual);
    }
    @Test
    void plainTest() throws Exception {
        String expect = getData("./src/test/resources/plainTestResult.txt");

        String pathfile1 = "./src/test/resources/filepath1.yml";
        String pathfile2 = "./src/test/resources/filepath2.yml";

        String actual = Differ.generate(pathfile1, pathfile2, "plain");

        assertEquals(expect, actual);
    }
}
